# Generated by Django 3.1.1 on 2020-09-02 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('position', models.CharField(choices=[('trainee', 'Стажер'), ('backend', 'Бэкенд'), ('pm', 'ПМ'), ('frontend', 'Фронтенд'), ('ios', 'IOS'), ('android', 'Андроид')], default='trainee', max_length=30, verbose_name='Позиция')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Личный email')),
                ('corporate_email', models.EmailField(max_length=254, verbose_name='Корпоративный email')),
                ('gitlab_account', models.CharField(max_length=200, verbose_name='Gitlab аккаунт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fired', models.BooleanField(default=False, verbose_name='Статус что сотрудник уволен')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен ли сотрудник')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден ли сотрудник')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер ли сотрудник')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
